name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    name: build-and-test-${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, windows-2022]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '3.1.x'

    - name: Restore dependencies
      run: dotnet restore src/Tesseract.sln

    - name: Build
      run: dotnet build src/Tesseract.sln --no-restore

    - name: Test
      run: dotnet test src/Tesseract.sln --no-build --verbosity normal
